[package]
name = "zimg"
version = "0.2.2"
authors = ["zaidejjo <zaidejjo@gmail.com>"]
description = "Pillow-style imaging for ZZ, powered by libvips"
license = "MIT"
repository = "https://github.com/zz-language/zimg"
category = "utilities"
keywords = ["zimg"]

[native]
build = "build.sh"
